---
- name: default
  hosts: all
  become: true
  tags:
    - default
  tasks:
    - import_tasks: tasks/default.yml

- name: default
  hosts: all
  tags:
    - default
  roles:
    - 1995parham-me

- name: domjudge
  hosts:
    - daavar.aut.ac.ir
  tags:
    - domserver
  vars:
    domserver: enabled
  roles:
    - domjudge-role

- name: domjudge
  hosts:
    - daavar.aut.ac.ir
  tags:
    - domserver
  tasks:
    - name: apache
      template:
        src: templates/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0755
