---
- name: default
  hosts: all
  become: true
  tags:
    - default
  tasks:
    - import_tasks: tasks/default.yml

- name: default
  hosts: all
  tags:
    - default
  roles:
    - 1995parham-me

- name: domjudge
  hosts:
    - daavar.aut.ac.ir
  tags:
    - domserver
  vars:
    domserver: enabled
    judgehost: enabled
    udgehost_domserver_url: http://localhost/domjudge/api
    judgehost_domserver_user: judgehost
    judgehost_domserver_pass: NP3FziLos2cHN0LN
  roles:
    - domjudge-role
