---
- name: default
  hosts: all
  become: true
  tags:
    - default
  tasks:
    - import_tasks: tasks/default.yml

- name: default
  hosts: all
  tags:
    - default
  roles:
    - 1995parham-me

- name: domjudge
  hosts:
    - daavar.aut.ac.ir
  tags:
    - domserver
  vars:
    domserver: enabled
    judgehost: enabled
  roles:
    - domjudge-role

- name: judgehost
  hosts:
    - jh-01.aut.ac.ir
  tags:
    - judgehost
  vars:
    domserver: disabled
    judgehost: enabled
    judgehost_domservers:
      - id: default
        url: http://172.25.157.155/domjudge/api
        user: judgehost
        pass: NP3FziLos2cHN0LN
  roles:
    - domjudge-role
