---
- name: install requirements
  become: true
  apt:
    name:
      - build-essential
      - acl
      - zip
      - unzip
      - mariadb-server
      - python3-mysqldb
      - nginx
      - php
      - php-fpm
      - php-gd
      - php-cli
      - php-intl
      - php-mbstring
      - php-mysql
      - php-curl
      - php-json
      - php-xml
      - php-zip
      - composer
      - ntp
      - libcgroup-dev

- name: starting and enabling the mariadb service
  service:
    name: mariadb
    state: started
    enabled: true

- name: setting up root credentials
  ignore_errors: true
  mysql_user:
    name: root
    password: "ceit_is_the_best"
    login_user: root
    login_host: "localhost"
    host: localhost
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
    state: present

- name: checking the root credentials
  mysql_user:
    name: root
    password: "ceit_is_the_best"
    login_user: root
    login_host: "localhost"
    login_password: "ceit_is_the_best"
    host: localhost
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
    state: present

- name: create Downloads directory
  become: false
  file:
    path: $HOME/Downloads
    state: directory

- name: download
  become: false
  ansible.builtin.unarchive:
    src: https://www.domjudge.org/releases/domjudge-{{version}}.tar.gz
    dest: $HOME/Downloads
    remote_src: true
    creates: $HOME/Downloads/domjudge-{{version}}

- name: configure
  become: false
  command: ./configure --prefix=$HOME/domjudge
  args:
    chdir: $HOME/Downloads/domjudge-{{version}}
    creates: paths.mk

- name: make
  become: false
  command: make domserver
  args:
    chdir: $HOME/Downloads/domjudge-{{version}}

- name: install
  become: false
  command: make install-domserver
  args:
    chdir: $HOME/Downloads/domjudge-{{version}}
